module.exports = {
  products: [
    {
      _id: '1',
      name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
      category: 'Shirts',
      image: '/images/product-1.jpg',
      price: 59,
      brand: 'Hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
      category: 'Shirts',
      image: '/images/product-2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 5,
      numReviews: 51,
    },
    {
      _id: '3',
      name: 'Adidas Mens Long Sleeve Hoodie',
      category: 'Shirts',
      image: '/images/product-3.jpg',
      price: 59,
      brand: 'Adidas',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'Under Armour Mens Sportstyle Tricot Joggers',
      category: 'Pants',
      image: '/images/product-4.jpg',
      price: 90,
      brand: 'Under Armour',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Champion Mens Graphic Powerblend Fleece Jogger',
      category: 'Pants',
      image: '/images/product-5.jpg',
      price: 119,
      brand: 'Champion',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
      category: 'Pants',
      image: '/images/product-6.jpg',
      price: 85,
      brand: 'Aelfric Eden',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
    {
    _id: '7',
          name: 'Lightning stud earrings',
          category: 'earrings',
          image: '/images/product-7.jpg',
          price: 375,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '8',
          name: 'Band ear cuff',
          category: 'earrings',
          image: '/images/product-8.jpg',
          price: 226,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '9',
          name: 'Spike hoop earrings',
          category: 'earrings',
          image: '/images/product-9.jpg',
          price: 447,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '10',
          name: 'Double loop earrings',
          category: 'earrings',
          image: '/images/product-10.jpg',
          price: 479,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '11',
          name: 'Horseshoe stud earrings',
          category: 'earrings',
          image: '/images/product-11.jpg',
          price: 380,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '12',
          name: 'Evil eye stud earrings',
          category: 'earrings',
          image: '/images/product-12.jpg',
          price: 371,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '13',
          name: 'Pegasus earrings',
          category: 'earrings',
          image: '/images/product-13.jpg',
          price:441,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '14',
          name: 'Cross stud earrings',
          category: 'earrings',
          image: '/images/product-14.jpg',
          price:304,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '15',
          name: 'Vase pendants',
          category: 'pendants',
          image: '/images/product-15.jpg',
          price:1217,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '17',
          name: 'Mini bell pendants',
          category: 'pendants',
          image: '/images/product-17.jpg',
          price:839,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '18',
          name: 'Bell pendants',
          category: 'pendants',
          image: '/images/product-18.jpg',
          price:1771,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '19',
          name: 'Wax seal letter pendants',
          category: 'pendants',
          image: '/images/product-19.jpg',
          price:419,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '20',
          name: 'Pine cone pendants',
          category: 'pendants',
          image: '/images/product-20.jpg',
          price:632,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '21',
          name: 'Hazelnut pendants',
          category: 'pendants',
          image: '/images/product-21.jpg',
          price:555,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '22',
          name: 'Good luck medallion pendants',
          category: 'pendants',
          image: '/images/product-22.jpg',
          price:707,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '23',
          name: 'Lucky Horn pendants',
          category: 'pendants',
          image: '/images/product-23.jpg',
          price:523,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '24',
          name: 'Signet ring',
          category:'rings',
          image: '/images/product-24.jpg',
          price:1087,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '25',
          name: 'Figure Eight ring',
          category:'rings',
          image: '/images/product-25.jpg',
          price:1060,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '26',
          name: 'Signet ring',
          category:'rings',
          image: '/images/product-26.jpg',
          price:1087,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '27',
          name: 'Bar ring',
          category:'rings',
          image: '/images/product-27.jpg',
          price:1030,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '28',
          name: 'Cross signet ring',
          category:'rings',
          image: '/images/product-28.jpg',
          price:762,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },{
    _id: '29',
          name: 'Lion signet ring',
          category:'rings',
          image: '/images/product-29.jpg',
          price:740,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '30',
          name: 'Sun signet ring',
          category:'rings',
          image: '/images/product-30.jpg',
          price:732,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '31',
          name: 'Skull ring',
          category:'rings',
          image: '/images/product-31.jpg',
          price:990,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '32',
          name: 'Narrow interlink chain bracelet',
          category: 'bracelets',
          image: '/images/product-32.jpg',
          price:186,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '33',
          name: 'Interlink chain bracelet',
          category: 'bracelets',
          image: '/images/product-33.jpg',
          price:570,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '34',
          name: 'Hex cuff bracelet',
          category: 'bracelets',
          image: '/images/product-34.jpg',
          price:21133,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '35',
          name: 'Stacking cuff  bracelet',
          category: 'bracelets',
          image: '/images/product-35.jpg',
          price:4114,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '36',
          name: 'Double leaf cuff bracelet',
          category: 'bracelets',
          image: '/images/product-36.jpg',
          price:7411,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '37',
          name: 'Narrow estrucan cuff bracelet',
          category: 'bracelets',
          image: '/images/product-37.jpg',
          price:2377,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '38',
          name: 'Signet cuff bracelet',
          category: 'bracelets',
          image: '/images/product-38.jpg',
          price:9321,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '39',
          name: 'Mini linear link chain bracelet',
          category: 'bracelets',
          image: '/images/product-39.jpg',
          price:2393,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '40',
          name: 'Narrow interlink chain',
          category: 'neckchains',
          image: '/images/product-40.jpg',
          price:584,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '41',
          name: 'Interlink chain',
          category: 'neckchains',
          image: '/images/product-41.jpg',
          price:1078,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '42',
          name: 'Mini linear link chain',
          category: 'neckchains',
          image: '/images/product-42.jpg',
          price:6938,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
    {
    _id: '43',
          name: 'Twisted rope necklace',
          category: 'neckchains',
          image: '/images/product-43.jpg',
          price:2845,
          brand: 'Aelfric Eden',
          rating: 4.5,
          numReviews: 45,
          countInStock: 6,
        },
  ],
};